from backend.app.processors.pdf_to_images import PdfToImagesProcessor
from backend.app.processors.images_to_pdf import ImagesToPdfProcessor

PdfToImageProcessor = PdfToImagesProcessor
PDFToImageProcessor = PdfToImagesProcessor
ImageToPDFProcessor = ImagesToPdfProcessor
