import React, { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { analyzePdfDocument, buildPresentationFromAnalysis, askDocumentQuestion, DocumentAnalysis } from '../services/analyzerService';
import { pdfToWord, pdfToExcel } from '../services/conversionService';
import FileUploader from '../components/FileUploader';
import { FileText, Sparkles, Presentation, Table, FileCode, CheckCircle2, ArrowRight, Download, MessageSquare, Clock, Layers, Hash, BookOpen, Send, RefreshCw } from 'lucide-react';
import { saveAs } from 'file-saver';
import { NotifySystem } from '../types';
import AdSlot from '../components/AdSlot';

interface AnalyzerPageProps {
  darkMode: boolean;
  notify: NotifySystem;
}

const AnalyzerPage: React.FC<AnalyzerPageProps> = ({ darkMode, notify }) => {
  const [file, setFile] = useState<File | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [analysis, setAnalysis] = useState<DocumentAnalysis | null>(null);
  const [buildingOutput, setBuildingOutput] = useState<string | null>(null);

  // Q&A state
  const [question, setQuestion] = useState('');
  const [chatHistory, setChatHistory] = useState<{ q: string; a: string }[]>([]);
  const [asking, setAsking] = useState(false);

  const handleFilesSelected = async (files: File[]) => {
    if (files.length === 0) return;
    const selectedFile = files[0];
    setFile(selectedFile);
    setAnalyzing(true);
    setAnalysis(null);
    setChatHistory([]);
    notify.upload();

    try {
      const result = await analyzePdfDocument(selectedFile);
      setAnalysis(result);
      notify.complete();
    } catch (err) {
      console.error('Analysis failed', err);
      notify.error();
    } finally {
      setAnalyzing(false);
    }
  };

  const handleAsk = async (queryToAsk?: string) => {
    const q = queryToAsk || question;
    if (!q.trim() || !analysis || asking) return;

    setAsking(true);
    if (!queryToAsk) setQuestion('');

    try {
      const answer = await askDocumentQuestion(q, analysis);
      setChatHistory(prev => [...prev, { q, a: answer }]);
      notify.success();
    } catch (err) {
      console.error('Ask question failed', err);
      notify.error();
    } finally {
      setAsking(false);
    }
  };

  // Builder actions
  const handleExportPPTX = async () => {
    if (!analysis) return;
    setBuildingOutput('pptx');
    try {
      const blob = await buildPresentationFromAnalysis(analysis);
      saveAs(blob, `${analysis.fileName.replace(/\.pdf$/i, '')}_presentation.pptx`);
      notify.complete();
    } catch (err) {
      console.error('PPTX build failed', err);
      notify.error();
    } finally {
      setBuildingOutput(null);
    }
  };

  const handleExportDOCX = async () => {
    if (!file) return;
    setBuildingOutput('docx');
    try {
      const bytes = await pdfToWord(file);
      const blob = new Blob([bytes as any], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
      saveAs(blob, `${file.name.replace(/\.pdf$/i, '')}_report.docx`);
      notify.complete();
    } catch (err) {
      console.error('DOCX build failed', err);
      notify.error();
    } finally {
      setBuildingOutput(null);
    }
  };

  const handleExportXLSX = async () => {
    if (!file) return;
    setBuildingOutput('xlsx');
    try {
      const bytes = await pdfToExcel(file);
      const blob = new Blob([bytes as any], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      saveAs(blob, `${file.name.replace(/\.pdf$/i, '')}_data.xlsx`);
      notify.complete();
    } catch (err) {
      console.error('XLSX build failed', err);
      notify.error();
    } finally {
      setBuildingOutput(null);
    }
  };

  const handleExportNotes = () => {
    if (!analysis) return;
    const content = `# Document Intelligence Notes: ${analysis.fileName}
Generated by PDFBolt (100% Private Client-Side AI)

## Document Statistics
- Pages: ${analysis.pageCount}
- Words: ${analysis.wordCount.toLocaleString()}
- Characters: ${analysis.characterCount.toLocaleString()}
- Estimated Reading Time: ~${analysis.estimatedReadTimeMinutes} minutes
- Detected Tables: ${analysis.tableCount}
- Embedded Images: ${analysis.imageCount}

## Core Topics
${analysis.topics.map(t => `- ${t}`).join('\n')}

## Executive Summary
${analysis.executiveSummary}

## Key Strategic Findings
${analysis.keyFindings.map((kf, i) => `${i + 1}. ${kf}`).join('\n')}
`;
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    saveAs(blob, `${analysis.fileName.replace(/\.pdf$/i, '')}_notes.md`);
    notify.complete();
  };

  const handleExportJSON = () => {
    if (!analysis) return;
    const blob = new Blob([JSON.stringify(analysis, null, 2)], { type: 'application/json' });
    saveAs(blob, `${analysis.fileName.replace(/\.pdf$/i, '')}_ast.json`);
    notify.complete();
  };

  return (
    <div className="animate-fadeIn pb-24">
      <Helmet>
        <title>AI PDF Analyzer & Multi-Output Builder | PDFBolt</title>
        <meta name="description" content="Deep structural PDF intelligence: Extract word counts, tables, topics, executive summaries, interactive Q&A, and 1-click generation of PPTX presentations and Word reports." />
        <link rel="canonical" href="https://pdfbolt.com/analyze-pdf" />
      </Helmet>

      {/* Hero Header */}
      <section className={`py-14 border-b ${darkMode ? 'border-slate-800 bg-slate-900/40' : 'border-slate-100 bg-slate-50/70'}`}>
        <div className="max-w-5xl mx-auto px-6 text-center">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-yellow-500/10 text-yellow-600 dark:text-yellow-400 font-black text-xs uppercase tracking-widest mb-4">
            <Sparkles size={14} /> PDF Intelligence + Creation Engine
          </div>
          <h1 className={`text-3xl md:text-5xl font-black mb-4 tracking-tight leading-tight ${darkMode ? 'text-white' : 'text-slate-900'}`}>
            AI PDF Analyzer & Multi-Output Builder
          </h1>
          <p className={`text-base md:text-lg max-w-2xl mx-auto ${darkMode ? 'text-slate-400' : 'text-slate-600'}`}>
            Understand any PDF instantly. Extract structure, topics, and key insights—then transform it into presentations, reports, or spreadsheets with a single click.
          </p>
        </div>
      </section>

      {/* Main Content Area */}
      <div className="max-w-6xl mx-auto px-6 py-12">
        {!analysis && (
          <div className="max-w-2xl mx-auto">
            {analyzing ? (
              <div className={`p-16 rounded-[2rem] border text-center ${darkMode ? 'bg-slate-800/50 border-slate-700' : 'bg-white border-slate-200 shadow-xl'}`}>
                <div className="w-14 h-14 border-4 border-yellow-500 border-t-transparent rounded-full animate-spin mx-auto mb-6"></div>
                <h2 className={`text-2xl font-black mb-2 ${darkMode ? 'text-white' : 'text-slate-900'}`}>
                  Analyzing Document Intelligence...
                </h2>
                <p className="text-xs text-slate-400 max-w-md mx-auto">
                  Extracting text streams, tabular grids, image operators, and generating topical executive insights...
                </p>
              </div>
            ) : (
              <FileUploader
                onFilesSelected={handleFilesSelected}
                accept=".pdf"
                multiple={false}
                darkMode={darkMode}
              />
            )}
          </div>
        )}

        {analysis && (
          <div className="space-y-10 animate-slideDown">
            {/* Header with Switch File */}
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-6 border-b border-slate-200 dark:border-slate-800">
              <div>
                <span className="text-[10px] font-black uppercase tracking-widest text-yellow-500">Analyzed Document</span>
                <h2 className={`text-2xl font-black ${darkMode ? 'text-white' : 'text-slate-900'}`}>
                  {analysis.fileName}
                </h2>
              </div>
              <button
                onClick={() => { setAnalysis(null); setFile(null); }}
                className={`px-4 py-2 rounded-xl text-xs font-bold border transition-colors flex items-center gap-2 ${
                  darkMode ? 'border-slate-700 text-slate-300 hover:bg-slate-800' : 'border-slate-200 text-slate-700 hover:bg-slate-100'
                }`}
              >
                <RefreshCw size={14} /> Analyze Another PDF
              </button>
            </div>

            {/* Metric Counters Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
              {[
                { label: 'Pages', val: analysis.pageCount, icon: <Layers size={18} className="text-yellow-500" /> },
                { label: 'Words', val: analysis.wordCount.toLocaleString(), icon: <FileText size={18} className="text-blue-500" /> },
                { label: 'Read Time', val: `~${analysis.estimatedReadTimeMinutes} min`, icon: <Clock size={18} className="text-emerald-500" /> },
                { label: 'Tables Detected', val: analysis.tableCount, icon: <Table size={18} className="text-purple-500" /> },
                { label: 'Images', val: analysis.imageCount, icon: <Sparkles size={18} className="text-amber-500" /> },
                { label: 'Characters', val: analysis.characterCount.toLocaleString(), icon: <Hash size={18} className="text-rose-500" /> },
              ].map((m, idx) => (
                <div key={idx} className={`p-5 rounded-2xl border ${darkMode ? 'bg-slate-800/40 border-slate-700' : 'bg-white border-slate-200 shadow-sm'}`}>
                  <div className="flex items-center gap-2 mb-2">{m.icon} <span className="text-[11px] font-bold text-slate-400 uppercase">{m.label}</span></div>
                  <div className={`text-xl font-black ${darkMode ? 'text-white' : 'text-slate-900'}`}>{m.val}</div>
                </div>
              ))}
            </div>

            {/* Core Topics */}
            <div className={`p-6 rounded-3xl border ${darkMode ? 'bg-slate-800/30 border-slate-800' : 'bg-slate-50 border-slate-200'}`}>
              <span className="text-[10px] font-black uppercase tracking-wider text-slate-400 block mb-3">Extracted Core Topics</span>
              <div className="flex flex-wrap gap-2">
                {analysis.topics.map((t, idx) => (
                  <span key={idx} className="px-3 py-1.5 rounded-xl bg-yellow-500/10 text-yellow-600 dark:text-yellow-400 text-xs font-black">
                    #{t}
                  </span>
                ))}
              </div>
            </div>

            {/* Executive Summary & Key Findings */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
              {/* Summary (7 cols) */}
              <div className={`lg:col-span-7 p-8 rounded-3xl border space-y-6 ${darkMode ? 'bg-slate-800/40 border-slate-700' : 'bg-white border-slate-200 shadow-sm'}`}>
                <h3 className={`text-lg font-black flex items-center gap-2 ${darkMode ? 'text-white' : 'text-slate-900'}`}>
                  <Sparkles className="text-yellow-500" size={20} /> Executive Summary
                </h3>
                <p className={`text-sm leading-relaxed ${darkMode ? 'text-slate-300' : 'text-slate-700'}`}>
                  {analysis.executiveSummary}
                </p>

                <div className="pt-4 border-t border-slate-200 dark:border-slate-800">
                  <h4 className={`text-xs font-black uppercase tracking-wider mb-4 ${darkMode ? 'text-slate-300' : 'text-slate-700'}`}>
                    Key Strategic Takeaways
                  </h4>
                  <ul className="space-y-2.5">
                    {analysis.keyFindings.map((kf, i) => (
                      <li key={i} className="flex items-start gap-2 text-xs leading-relaxed">
                        <CheckCircle2 size={16} className="text-emerald-500 flex-shrink-0 mt-0.5" />
                        <span className={darkMode ? 'text-slate-300' : 'text-slate-600'}>{kf}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Multi-Output PDF Builder Panel (5 cols) */}
              <div className={`lg:col-span-5 p-8 rounded-3xl border flex flex-col justify-between ${
                darkMode ? 'bg-gradient-to-br from-slate-900 to-slate-800 border-yellow-500/30' : 'bg-gradient-to-br from-yellow-50 to-amber-50 border-yellow-200 shadow-lg'
              }`}>
                <div>
                  <span className="text-[10px] font-black uppercase tracking-widest text-yellow-600 dark:text-yellow-400">
                    PDF Builder Pipeline
                  </span>
                  <h3 className={`text-xl font-black mt-1 mb-2 ${darkMode ? 'text-white' : 'text-slate-900'}`}>
                    Transform into New Formats
                  </h3>
                  <p className={`text-xs mb-6 ${darkMode ? 'text-slate-400' : 'text-slate-600'}`}>
                    Convert this document into ready-to-share presentations, reports, and spreadsheets.
                  </p>

                  <div className="space-y-3">
                    <button
                      onClick={handleExportPPTX}
                      disabled={!!buildingOutput}
                      className="w-full py-3 px-4 bg-yellow-500 hover:bg-yellow-400 disabled:opacity-50 text-slate-950 font-black text-xs uppercase tracking-wider rounded-xl transition-all flex items-center justify-between shadow-md"
                    >
                      <span className="flex items-center gap-2"><Presentation size={16} /> 10-Slide PPTX Deck</span>
                      <Download size={14} />
                    </button>

                    <button
                      onClick={handleExportDOCX}
                      disabled={!!buildingOutput}
                      className={`w-full py-3 px-4 rounded-xl font-bold text-xs uppercase tracking-wider transition-all flex items-center justify-between border ${
                        darkMode ? 'bg-slate-800 border-slate-700 text-white hover:bg-slate-700' : 'bg-white border-slate-300 text-slate-800 hover:bg-slate-50'
                      }`}
                    >
                      <span className="flex items-center gap-2"><FileText size={16} /> Formatted Word Report</span>
                      <Download size={14} />
                    </button>

                    <button
                      onClick={handleExportXLSX}
                      disabled={!!buildingOutput}
                      className={`w-full py-3 px-4 rounded-xl font-bold text-xs uppercase tracking-wider transition-all flex items-center justify-between border ${
                        darkMode ? 'bg-slate-800 border-slate-700 text-white hover:bg-slate-700' : 'bg-white border-slate-300 text-slate-800 hover:bg-slate-50'
                      }`}
                    >
                      <span className="flex items-center gap-2"><Table size={16} /> Extracted Excel Tables</span>
                      <Download size={14} />
                    </button>

                    <div className="flex gap-2 pt-2">
                      <button
                        onClick={handleExportNotes}
                        className={`flex-1 py-2.5 rounded-xl font-bold text-[11px] uppercase border text-center ${
                          darkMode ? 'border-slate-700 text-slate-300 hover:bg-slate-800' : 'border-slate-200 text-slate-700 hover:bg-white'
                        }`}
                      >
                        Study Notes (MD)
                      </button>
                      <button
                        onClick={handleExportJSON}
                        className={`flex-1 py-2.5 rounded-xl font-bold text-[11px] uppercase border text-center ${
                          darkMode ? 'border-slate-700 text-slate-300 hover:bg-slate-800' : 'border-slate-200 text-slate-700 hover:bg-white'
                        }`}
                      >
                        Document JSON
                      </button>
                    </div>
                  </div>
                </div>

                <div className="pt-6 border-t border-slate-200/60 dark:border-slate-700 mt-6 flex items-center justify-between text-[11px] text-slate-400">
                  <span>100% Client-Side Engine</span>
                  <span className="text-emerald-500 font-bold">✓ Zero Data Upload</span>
                </div>
              </div>
            </div>

            {/* Interactive Ask-PDF Section */}
            <div className={`p-8 rounded-3xl border space-y-6 ${darkMode ? 'bg-slate-800/40 border-slate-700' : 'bg-white border-slate-200 shadow-sm'}`}>
              <div>
                <h3 className={`text-xl font-black flex items-center gap-2 mb-1 ${darkMode ? 'text-white' : 'text-slate-900'}`}>
                  <MessageSquare className="text-yellow-500" size={22} /> Ask Anything About This PDF
                </h3>
                <p className={`text-xs ${darkMode ? 'text-slate-400' : 'text-slate-500'}`}>
                  Query tables, specific page figures, or request summaries directly from the text stream.
                </p>
              </div>

              {/* Suggested Questions */}
              <div className="flex flex-wrap gap-2">
                {analysis.suggestedQuestions.map((sq, i) => (
                  <button
                    key={i}
                    onClick={() => handleAsk(sq)}
                    disabled={asking}
                    className={`px-3 py-1.5 rounded-xl text-xs font-semibold border transition-all text-left ${
                      darkMode ? 'border-slate-700 text-slate-300 hover:border-yellow-500' : 'border-slate-200 text-slate-600 hover:border-yellow-500'
                    }`}
                  >
                    "{sq}"
                  </button>
                ))}
              </div>

              {/* Chat Thread */}
              {chatHistory.length > 0 && (
                <div className="space-y-4 pt-4 border-t border-slate-100 dark:border-slate-800">
                  {chatHistory.map((item, idx) => (
                    <div key={idx} className="space-y-2">
                      <div className="flex items-start gap-2 text-xs font-bold text-yellow-600 dark:text-yellow-400">
                        <span>You:</span> <span>{item.q}</span>
                      </div>
                      <div className={`p-4 rounded-2xl text-xs leading-relaxed ${
                        darkMode ? 'bg-slate-900 text-slate-200' : 'bg-slate-50 text-slate-800'
                      }`}>
                        {item.a}
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* Input Form */}
              <form
                onSubmit={(e) => { e.preventDefault(); handleAsk(); }}
                className="flex gap-2"
              >
                <input
                  type="text"
                  value={question}
                  onChange={(e) => setQuestion(e.target.value)}
                  placeholder="Ask a question about this document..."
                  disabled={asking}
                  className={`flex-grow px-4 py-3.5 rounded-xl border text-xs font-semibold outline-none focus:ring-2 focus:ring-yellow-500 ${
                    darkMode ? 'bg-slate-900 border-slate-700 text-white' : 'bg-slate-50 border-slate-200 text-slate-900'
                  }`}
                />
                <button
                  type="submit"
                  disabled={asking || !question.trim()}
                  className="px-6 py-3.5 bg-yellow-500 hover:bg-yellow-400 disabled:opacity-50 text-slate-950 font-black text-xs uppercase tracking-wider rounded-xl shadow-md transition-all flex items-center gap-2"
                >
                  <Send size={14} /> {asking ? 'Thinking...' : 'Ask'}
                </button>
              </form>
            </div>

            {/* Non-Intrusive Result Screen Sponsored Slot (Far below analysis actions) */}
            <AdSlot placement="RESULT_BOTTOM" />
          </div>
        )}
      </div>
    </div>
  );
};

export default AnalyzerPage;
